export const tables = {
    productCategories: "product_categories",
    storeProductCategories: "store_product_categories",
    stores: "stores",
    products: "products",
    merchants: "merchants",
    merchantStaffs: "merchant_staffs",
    roles: "roles",
    permissions: "permissions",
    permissionsForRoles: "permissions_for_roles",
    merchantBankAccounts: "merchant_bank-accounts",
    merchantBillings: "merchant_billings",
    merchantCards: "merchant_cards",
    merchantCharges: "merchant_charges",
    merchantPayouts: "merchant_payout",
    merchantTransactions: "merchant_transactions",
    merchantUsages: "merchant_usages",
    usageCategories: "usage_categories",
    usages: "usages"
};
